### 数组的创建

[1 2 3]
(3, 4)
[[1000 1000 1000 1000]
 [1000 1000 1000 1000]
 [1000 1000 1000 1000]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727

In [25]:
import numpy as np

vector01 = np.array([1, 2, 3]).reshape(1, -1)
vector02 = np.array([4, 5, 6]).reshape(-1, 1)

print(vector01.shape)
print(vector02.shape)

print(vector01 @ vector02)

(1, 3)
(3, 1)
[[32]]


In [38]:
import numpy as np

matrix = np.arange(0, 16).reshape(4, 4)

print(matrix[:, 0])

mask = matrix > 7
mask1 = ~mask
print(mask1)
print(matrix[mask1])


[ 0  4  8 12]
[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]
 [False False False False]]
[0 1 2 3 4 5 6 7]
